import {
  PawPrint,
  LayoutDashboard,
  Cat,
  MapPin,
  BarChart3,
  Download,
  Users,
  FileInput,
  Bell,
  ArrowRight,
  Menu,
  X,
  UserCircle,
  Search,
  ChevronDown,
  Edit,
  Trash2,
  Plus,
} from "lucide-react";

const Icons = {
  Paw: PawPrint,
  Dashboard: LayoutDashboard,
  Cats: Cat,
  Colonies: MapPin,
  Sightings: PawPrint,
  Stats: BarChart3,
  Export: Download,
  Users: Users,
  Import: FileInput,
  Bell: Bell,
  ArrowRight: ArrowRight,
  Menu: Menu,
  Close: X,
  UserCircle: UserCircle,
  Search: Search,
  ChevronDown: ChevronDown,
  Edit: Edit,
  Trash2: Trash2,
  Plus: Plus,
};

export default Icons;
